### PR TITLE
Added functionlity for endpoint summaries

### PR DESCRIPTION
**Pull request by evanpilling**
Added functionlity so that endpoint summaries can be automatically generated with the OpenAI API. Resolves issue #6

### CODE REVIEW

**Comment by evanpilling** [comment]
P.S. commit is going to look larger than it actually is due to running "mvn clean -e install" to generate executables in order to run the required scripts. Only actual files changed were EndPointOperationObj.java and pom.xml.

**Review by jerhe3 — APPROVED** [review]
Changes to the code look good to me, might want to include in the documentation/prompting that an openAI key needs to be provided in order for the summaries to work correctly.

**Comment by RyanGarfinkel** [comment]
Do we want to gitignore the logs and json files in source/generated?

**Comment by evanpilling** [comment]
I think it's fine. The json files and logs can be good examples of expected output and the executables are useful since we dockerized it.

**Pull request merged**
